### ISSUE TITLE
пунктуация в п. 13.2 Изоляция транзакций

### ISSUE THREAD

**Issue by olshevskiy87** [pluzanov/pg-doc-ru#75]
п.13.2.2

> Если же первая транзакция зафиксировалась, и в результате изменила или удалила эту строку, а не просто заблокировала её, произойдёт откат текущей транзакции с сообщением

мне кажется, что запятая перед союзом "и" лишняя, потому что

> первая транзакция зафиксировалась, и в результате изменила или удалила эту строку

это предложение с однородными сказуемыми. поправьте, если ошибаюсь.

**Comment by alexanderlaw** [comment]
Спасибо за замечание!
Исправлено в https://github.com/pluzanov/pg-doc-ru/commit/3f4953cefa9275c3470018a7ddd43c5608a1632b
